version: '3'

volumes:
  postgres_data_local: {}

services:
  django:
    container_name: pdk-django
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
    - postgres
    env_file:
    - variables.env
    command: sh -c "sleep 10 && gunicorn filterbubble.wsgi --bind 0.0.0.0:80"

  postgres:
    image: mdillon/postgis:9.6
    container_name: pdk-postgres
    volumes:
    - postgres_data_local:/var/lib/postgresql/data
    env_file:
    - variables.env
    ports:
    - "5432:5432"

  nginx_ssl:
    image: rsdnlesc/docker-term-letsencrypt
    volumes:
    - ./cert:/cert
    - ./letsencrypt:/etc/letsencrypt
    env_file:
    - variables.env
    restart: unless-stopped
    depends_on:
    - nginx
    ports:
    - 8132:443
    - 80:80

  nginx:
    image: nginx:1.15.8-alpine
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off;'
    depends_on:
      - django
